- alias: Michi Bodenlicht - Schalter
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001548923
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.sonoff